name: Publish package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Set tagged version
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}
      - name: Publish package
        run: mvn --batch-mode deploy --file pom.xml --settings settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USENAME: ${{github.actor}}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

